version: "3.7"

services:
  broker:
    image: redis:7
    restart: always

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless
    volumes:
      - paperless_db:/var/lib/postgresql/data

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: always
    depends_on:
      - db
      - broker
    ports:
      - "8000:8000"
    volumes:
      - paperless_data:/usr/src/paperless/data
      - paperless_media:/usr/src/paperless/media
      - paperless_export:/usr/src/paperless/export
      - paperless_consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_DBUSER: paperless
      PAPERLESS_DBPASS: paperless
      PAPERLESS_DBNAME: paperless
      PAPERLESS_SECRET_KEY: changeme_in_production
      PAPERLESS_TIME_ZONE: Europe/Berlin
      PAPERLESS_URL: https://${YOUR_DOMAIN}/
      USERMAP_UID: 1000
      USERMAP_GID: 1000

volumes:
  paperless_data:
  paperless_media:
  paperless_export:
  paperless_consume:
  paperless_db:
