name: Cleanup Orphaned SSH Keys

on:
  workflow_dispatch:  # Allows manual trigger in the GitHub UI

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Install Hetzner CLI
        run: |
          curl -O https://github.com/hetznercloud/cli/releases/download/v1.36.0/hcloud-linux-amd64.tar.gz
          tar -xzf hcloud-linux-amd64.tar.gz
          sudo mv hcloud /usr/local/bin/

      - name: Delete old SSH keys with prefix "paperless-key"
        env:
          HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
        run: |
          echo "Fetching and deleting SSH keys matching 'paperless-key*'..."

          hcloud ssh-key list --output json --token "$HCLOUD_TOKEN" |
            jq -c '.[] | select(.name | startswith("paperless-key"))' |
            while read -r key; do
              key_id=$(echo "$key" | jq -r '.id')
              key_name=$(echo "$key" | jq -r '.name')

              echo "🗑️  Deleting SSH key: $key_name (ID: $key_id)"
              hcloud ssh-key delete "$key_id" --token "$HCLOUD_TOKEN"
            done

          echo "✅ Cleanup complete."
